"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronRight, Fan, Gauge, Layers3, ShieldCheck, Snowflake, Wrench } from "lucide-react";
import type { HomePageProps } from "@/templates/types";

const EASE = [0.22, 1, 0.36, 1] as const;
const str = (p: Record<string, unknown>, k: string) => (typeof p[k] === "string" ? (p[k] as string) : "");
const arr = (p: Record<string, unknown>, k: string) => (Array.isArray(p[k]) ? (p[k] as string[]) : []);
const fv = (i: number) => ({ initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.55, delay: i * 0.08, ease: EASE } }) as const;

export function Template06HomePage({ modules, products, categories, blogPosts }: HomePageProps) {
  return (
    <div className="t06 bg-[#f6f8fb] text-[#122033] antialiased">
      <style>{`.t06-wrap{max-width:1200px;margin:0 auto;padding:0 24px}.t06-sec{padding:92px 0}.t06-tag{display:inline-block;padding:4px 12px;border:1px solid #cdd8e6;border-radius:999px;background:#eef4fa;color:#2563eb;font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.t06-card{background:#fff;border:1px solid #dbe4ee;border-radius:14px;overflow:hidden;transition:transform .2s,border-color .2s}.t06-card:hover{transform:translateY(-4px);border-color:#60a5fa}`}</style>
      {modules.map((m) => {
        const p = m.payloadJson ?? {};
        if (m.moduleKey === "hero") return <section key="hero" className="t06-sec relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(96,165,250,.16),transparent_38%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,.12),transparent_35%)]" /><div className="t06-wrap relative z-10 grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><span {...fv(0)} className="t06-tag mb-6">{str(p, "eyebrow") || "HVAC & Fluid Engineering"}</span><motion.h1 {...fv(1)} className="max-w-3xl text-5xl font-black leading-[1.06] tracking-tight md:text-6xl">{str(p, "title") || "Efficient Fluid and HVAC Solutions for Industrial Facilities"}</motion.h1><motion.p {...fv(2)} className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{str(p, "description") || "Delivering piping systems, air handling equipment, and custom components with reliable technical support."}</motion.p><motion.div {...fv(3)} className="mt-10 flex flex-wrap gap-4"><Link href={str(p, "primaryCtaHref") || "/contact"} className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-white hover:bg-blue-500">{str(p, "primaryCtaLabel") || "Request Engineering Support"}<ArrowRight className="h-4 w-4" /></Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-slate-700 hover:border-blue-400">Browse Products <ChevronRight className="h-4 w-4" /></Link></motion.div></div><motion.div {...fv(1)} className="grid gap-4 sm:grid-cols-2"><div className="t06-card p-6"><Fan className="h-6 w-6 text-blue-600" /><h3 className="mt-4 text-lg font-bold">Air handling</h3><p className="mt-2 text-sm leading-6 text-slate-600">Ventilation and cooling support for manufacturing and commercial systems.</p></div><div className="t06-card p-6"><Wrench className="h-6 w-6 text-blue-600" /><h3 className="mt-4 text-lg font-bold">Custom fabrication</h3><p className="mt-2 text-sm leading-6 text-slate-600">Configured parts and assemblies matched to project specifications.</p></div><div className="t06-card p-6"><Gauge className="h-6 w-6 text-blue-600" /><h3 className="mt-4 text-lg font-bold">Performance focus</h3><p className="mt-2 text-sm leading-6 text-slate-600">Designed for stable flow, pressure control, and energy-efficient operation.</p></div><div className="t06-card p-6"><Snowflake className="h-6 w-6 text-blue-600" /><h3 className="mt-4 text-lg font-bold">Thermal systems</h3><p className="mt-2 text-sm leading-6 text-slate-600">Heating and cooling components for variable facility requirements.</p></div></motion.div></div></section>;
        if (m.moduleKey === "trust-signals") { const items = arr(p, "items").length ? arr(p, "items") : ["Technical sizing support", "Reliable packaging for long-haul export", "Project-based customization available"]; return <section key="trust-signals" className="border-y border-slate-200 bg-white py-7"><div className="t06-wrap flex flex-wrap items-center justify-center gap-7 md:justify-between">{items.map((item, i) => <motion.div key={i} {...fv(i)} className="flex items-center gap-3 text-sm text-slate-600"><ShieldCheck className="h-4 w-4 text-blue-600" /><span>{item}</span></motion.div>)}</div></section>; }
        if (m.moduleKey === "featured-categories") { const slugs = arr(p, "slugs"); const featured = slugs.length ? categories.filter((c) => slugs.includes(c.slug)) : categories.slice(0, 4); if (!featured.length) return null; return <section key="featured-categories" className="t06-sec"><div className="t06-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t06-tag">Product Categories</span><h2 className="mt-4 text-3xl font-black md:text-4xl">HVAC & Fluid <span className="text-blue-600">Categories</span></h2></motion.div><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{featured.map((c, i) => <motion.div key={c.slug} {...fv(i)}><Link href={`/products/${c.slug}`} className="t06-card block h-full p-6"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Layers3 className="h-5 w-5" /></div><h3 className="text-lg font-bold">{c.nameEn}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.summaryEn}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-blue-600">Explore <ArrowRight className="h-3.5 w-3.5" /></span></Link></motion.div>)}</div></div></section>; }
        if (m.moduleKey === "factory-capability") return <section key="factory-capability" className="t06-sec border-y border-slate-200 bg-white"><div className="t06-wrap grid gap-16 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><motion.div {...fv(0)}><span className="t06-tag">Factory Capability</span><h2 className="mt-4 text-3xl font-black md:text-4xl">{str(p, "title") || "Built for project delivery"}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-600">{str(p, "description") || "In-house fabrication and assembly help manage schedule, quality, and customization requirements."}</p><ul className="mt-8 space-y-3">{["Flow and pressure calculations","Custom pipework and duct fabrication","Pump, valve, and fan integration","Testing and shipment documentation"].map((item) => <li key={item} className="flex items-start gap-3 text-sm text-slate-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-blue-600" />{item}</li>)}</ul></motion.div><motion.div {...fv(1)} className="grid grid-cols-2 gap-4">{[{v:"12,000㎡",l:"Factory Area"},{v:"60+",l:"Technicians"},{v:"35+",l:"Export Markets"},{v:"20-40d",l:"Typical Lead Time"}].map((s) => <div key={s.l} className="t06-card p-6"><div className="text-2xl font-black text-blue-600">{s.v}</div><div className="mt-1 text-xs uppercase tracking-widest text-slate-500">{s.l}</div></div>)}</motion.div></div></section>;
        if (m.moduleKey === "quality-certifications") return <section key="quality-certifications" className="t06-sec"><div className="t06-wrap"><motion.div {...fv(0)} className="mb-10"><span className="t06-tag">Quality & Compliance</span><h2 className="mt-4 text-3xl font-black md:text-4xl">Validation for Critical Systems</h2></motion.div><div className="grid gap-6 md:grid-cols-3">{["Pressure testing support","Material traceability","Project documentation packages"].map((item, i) => <motion.div key={item} {...fv(i)} className="t06-card p-6"><ShieldCheck className="h-6 w-6 text-blue-600" /><h3 className="mt-4 text-base font-bold">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Controls and records designed to reduce commissioning risk.</p></motion.div>)}</div></div></section>;
        if (m.moduleKey === "process-steps") { const items = arr(p, "items").length ? arr(p, "items") : ["Requirement review", "System design", "Build & test", "Shipment and support"]; return <section key="process-steps" className="t06-sec border-y border-slate-200 bg-white"><div className="t06-wrap"><motion.div {...fv(0)} className="mb-12 text-center"><span className="t06-tag">Delivery Process</span><h2 className="mt-4 text-3xl font-black md:text-4xl">From Specification to Commissioning</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{items.map((step, i) => <motion.div key={step} {...fv(i)} className="t06-card p-6"><div className="mb-3 text-3xl font-black text-blue-600/40">{`0${i + 1}`}</div><p className="text-sm text-slate-700">{step}</p></motion.div>)}</div></div></section>; }
        return null;
      })}
      {products.length > 0 && <section className="t06-sec border-y border-slate-200 bg-white"><div className="t06-wrap"><motion.div {...fv(0)} className="mb-12 flex items-end justify-between"><div><span className="t06-tag">Featured Products</span><h2 className="mt-4 text-3xl font-black md:text-4xl">Core Components</h2></div></motion.div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0, 6).map((product, i) => <motion.div key={product.slug} {...fv(i)}><Link href={`/products/${product.categorySlug}/${product.slug}`} className="t06-card block h-full"><div className="relative aspect-[4/3] bg-slate-100">{product.coverImageUrl ? <img src={product.coverImageUrl} alt={product.coverImageAlt ?? product.nameEn} className="h-full w-full object-cover" /> : <div className="absolute inset-0 flex items-center justify-center text-slate-300"><Wrench className="h-12 w-12" /></div>}</div><div className="p-5"><h3 className="mb-1 text-base font-bold">{product.nameEn}</h3><p className="mb-4 line-clamp-2 text-xs leading-relaxed text-slate-600">{product.shortDescriptionEn ?? ""}</p><span className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-blue-600">Details <ChevronRight className="h-3.5 w-3.5" /></span></div></Link></motion.div>)}</div></div></section>}
      {blogPosts.length > 0 && <section className="t06-sec border-y border-slate-200 bg-white"><div className="t06-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t06-tag">Insights</span><h2 className="mt-4 text-3xl font-black md:text-4xl">Engineering Notes</h2></motion.div><div className="grid gap-6 lg:grid-cols-3">{blogPosts.slice(0, 3).map((post, i) => <motion.div key={post.slug} {...fv(i)}><Link href={`/blog/${post.slug}`} className="t06-card block h-full p-7"><h3 className="text-base font-semibold">{post.titleEn}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{post.excerptEn ?? ""}</p></Link></motion.div>)}</div></div></section>}
      <section className="t06-sec-sm bg-gradient-to-r from-blue-700 to-cyan-600"><div className="t06-wrap text-center"><motion.div {...fv(0)} className="mx-auto max-w-2xl"><h2 className="mb-4 text-3xl font-black md:text-4xl">Planning a fluid system project?</h2><p className="mb-8 text-cyan-100">Tell us your flow rate, pressure requirements, site conditions, and destination market for a tailored proposal.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded bg-white px-8 py-3.5 text-sm font-black uppercase tracking-wider text-blue-700">Send Requirements <ArrowRight className="h-4 w-4" /></Link><Link href="/request-quote" className="inline-flex items-center gap-2 rounded border border-white/50 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-white">Request Quote Form</Link></div></motion.div></div></section>
    </div>
  );
}
