export const defaultFieldDefinitions = [
  {
    fieldKey: "model",
    labelZh: "鍨嬪彿",
    labelEn: "Model",
    inputType: "text",
    sortOrder: 10,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "material",
    labelZh: "鏉愭枡",
    labelEn: "Material",
    inputType: "text",
    sortOrder: 20,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "process",
    labelZh: "宸ヨ壓",
    labelEn: "Process",
    inputType: "text",
    sortOrder: 30,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "size",
    labelZh: "灏哄",
    labelEn: "Size",
    inputType: "text",
    sortOrder: 40,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "tolerance",
    labelZh: "鍏樊",
    labelEn: "Tolerance",
    inputType: "text",
    sortOrder: 50,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "surface_treatment",
    labelZh: "琛ㄩ潰澶勭悊",
    labelEn: "Surface Treatment",
    inputType: "text",
    sortOrder: 60,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "color",
    labelZh: "棰滆壊",
    labelEn: "Color",
    inputType: "text",
    sortOrder: 70,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "application",
    labelZh: "搴旂敤",
    labelEn: "Application",
    inputType: "textarea",
    sortOrder: 80,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "moq",
    labelZh: "鏈€灏忚捣璁㈤噺",
    labelEn: "MOQ",
    inputType: "text",
    sortOrder: 90,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "sample_lead_time",
    labelZh: "鎵撴牱鏃堕棿",
    labelEn: "Sample Lead Time",
    inputType: "text",
    sortOrder: 100,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "lead_time",
    labelZh: "浜よ揣鍛ㄦ湡",
    labelEn: "Lead Time",
    inputType: "text",
    sortOrder: 110,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "packaging",
    labelZh: "鍖呰鏂瑰紡",
    labelEn: "Packaging",
    inputType: "text",
    sortOrder: 120,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "place_of_origin",
    labelZh: "浜у湴",
    labelEn: "Place of Origin",
    inputType: "text",
    sortOrder: 130,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "supply_ability",
    labelZh: "渚涜揣鑳藉姏",
    labelEn: "Supply Ability",
    inputType: "text",
    sortOrder: 140,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "certification",
    labelZh: "璁よ瘉",
    labelEn: "Certification",
    inputType: "text",
    sortOrder: 150,
    isVisibleByDefault: true,
  },
] as const;

export type DefaultFieldDefinition = (typeof defaultFieldDefinitions)[number];
export type DefaultFieldKey = DefaultFieldDefinition["fieldKey"];
