export const defaultFieldDefinitions = [
  {
    fieldKey: "model",
    labelZh: "型号",
    labelEn: "Model",
    inputType: "text",
    sortOrder: 10,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "material",
    labelZh: "材料",
    labelEn: "Material",
    inputType: "text",
    sortOrder: 20,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "process",
    labelZh: "工艺",
    labelEn: "Process",
    inputType: "text",
    sortOrder: 30,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "size",
    labelZh: "尺寸",
    labelEn: "Size",
    inputType: "text",
    sortOrder: 40,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "tolerance",
    labelZh: "公差",
    labelEn: "Tolerance",
    inputType: "text",
    sortOrder: 50,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "surface_treatment",
    labelZh: "表面处理",
    labelEn: "Surface Treatment",
    inputType: "text",
    sortOrder: 60,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "color",
    labelZh: "颜色",
    labelEn: "Color",
    inputType: "text",
    sortOrder: 70,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "application",
    labelZh: "应用",
    labelEn: "Application",
    inputType: "textarea",
    sortOrder: 80,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "moq",
    labelZh: "最小起订量",
    labelEn: "MOQ",
    inputType: "text",
    sortOrder: 90,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "sample_lead_time",
    labelZh: "打样时间",
    labelEn: "Sample Lead Time",
    inputType: "text",
    sortOrder: 100,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "lead_time",
    labelZh: "交货周期",
    labelEn: "Lead Time",
    inputType: "text",
    sortOrder: 110,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "packaging",
    labelZh: "包装方式",
    labelEn: "Packaging",
    inputType: "text",
    sortOrder: 120,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "place_of_origin",
    labelZh: "产地",
    labelEn: "Place of Origin",
    inputType: "text",
    sortOrder: 130,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "supply_ability",
    labelZh: "供货能力",
    labelEn: "Supply Ability",
    inputType: "text",
    sortOrder: 140,
    isVisibleByDefault: true,
  },
  {
    fieldKey: "certification",
    labelZh: "认证",
    labelEn: "Certification",
    inputType: "text",
    sortOrder: 150,
    isVisibleByDefault: true,
  },
] as const;

export type DefaultFieldDefinition = (typeof defaultFieldDefinitions)[number];
export type DefaultFieldKey = DefaultFieldDefinition["fieldKey"];
