/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  INDUSTRY INIT — Phase 3: Upload Images to R2 + Link to Database        ║
 * ║                                                                          ║
 * ║  Prerequisites:                                                          ║
 * ║    ✅ Phase 1: npx tsx scripts/industry-init/run.ts --config xxx        ║
 * ║    ✅ Phase 2: Antigravity has generated all images in generated-images/ ║
 * ║                                                                          ║
 * ║  Usage:                                                                  ║
 * ║    npx tsx scripts/industry-init/upload-images.ts                       ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

import { config as loadDotenv } from "dotenv";
import { resolve } from "path";
loadDotenv({ path: resolve(process.cwd(), ".env.local") });
loadDotenv({ path: resolve(process.cwd(), ".env") });

import { existsSync, readdirSync, readFileSync } from "fs";
import { join, basename } from "path";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { eq } from "drizzle-orm";
import * as schema from "../../src/db/schema";
import { uploadToR2 } from "./lib/r2";
import type { ImageManifest, ImageManifestItem } from "./types";

const OUT_DIR = join(process.cwd(), "scripts", "industry-init");
const IMAGES_DIR = join(OUT_DIR, "generated-images");
const MANIFEST_FILE = join(OUT_DIR, "image-manifest.json");

function getDb() {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) throw new Error("DATABASE_URL is not set");
  return drizzle(neon(dbUrl), { schema });
}

async function main() {
  console.log("\n");
  console.log("═══════════════════════════════════════════════════════════");
  console.log("  📤  Phase 3: Upload Images to R2 + Link Database");
  console.log("═══════════════════════════════════════════════════════════\n");

  // ── Validate prerequisites ───────────────────────────────────────────────
  if (!existsSync(MANIFEST_FILE)) {
    console.error("❌ image-manifest.json not found.");
    console.error("   Run Phase 1 first: npx tsx scripts/industry-init/run.ts --config xxx");
    process.exit(1);
  }

  if (!existsSync(IMAGES_DIR)) {
    console.error("❌ generated-images/ directory not found.");
    console.error("   Images must be generated by Antigravity in Phase 2 first.");
    process.exit(1);
  }

  const manifest: ImageManifest = JSON.parse(readFileSync(MANIFEST_FILE, "utf8"));
  const generatedFiles = readdirSync(IMAGES_DIR).filter(
    (f) => f.endsWith(".webp") || f.endsWith(".jpg") || f.endsWith(".png"),
  );

  console.log(`📋 Manifest: ${manifest.totalImages} images expected`);
  console.log(`📁 Generated: ${generatedFiles.length} files found in generated-images/`);
  console.log("");

  if (generatedFiles.length === 0) {
    console.error("❌ No images found in generated-images/");
    console.error("   Ask Antigravity to generate images from image-manifest.json first.");
    process.exit(1);
  }

  const db = getDb();
  let uploaded = 0;
  let linked = 0;
  let failed = 0;

  // ── Process each generated image file ────────────────────────────────────
  for (const filename of generatedFiles.sort()) {
    const localPath = join(IMAGES_DIR, filename);

    // Find corresponding manifest entry
    const manifestItem = manifest.images.find((img) => img.filename === filename);
    if (!manifestItem) {
      console.warn(`  ⚠  ${filename} — not in manifest, skipping`);
      continue;
    }

    try {
      process.stdout.write(`  [${String(manifestItem.id).padStart(2, "0")}] ${filename} → `);

      // 1. Upload to R2
      const r2Key = `industry-init/${manifest.industry}/${filename}`;
      const r2Url = await uploadToR2({ localPath, r2Key });
      uploaded++;
      process.stdout.write(`R2 ✓ → `);

      // 2. Insert mediaAssets record
      const [mediaAsset] = await db
        .insert(schema.mediaAssets)
        .values({
          assetType: "image",
          bucketKey: r2Key,
          url: r2Url,
          fileName: filename,
          mimeType: "image/webp",
          fileSize: 0, // not critical
          width: manifestItem.width,
          height: manifestItem.height,
        })
        .onConflictDoUpdate({
          target: schema.mediaAssets.bucketKey,
          set: { url: r2Url, width: manifestItem.width, height: manifestItem.height },
        })
        .returning({ id: schema.mediaAssets.id });

      // 3. Link to the correct table
      await linkImageToRecord(db, manifestItem, r2Url, mediaAsset.id);
      linked++;
      console.log(`DB linked ✅`);
    } catch (err) {
      failed++;
      console.log(`FAILED ❌`);
      console.error(`     Error: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log("\n═══════════════════════════════════════════════════════════");
  console.log(`  ✅  Upload Complete!`);
  console.log("═══════════════════════════════════════════════════════════");
  console.log(`
  📊 Results:
     • Uploaded to R2:   ${uploaded}/${generatedFiles.length}
     • Linked to DB:     ${linked}/${generatedFiles.length}
     • Failed:           ${failed}

  🌐 Frontend will display real images after Next.js revalidates cache.
     Run: npm run build  OR  touch src/app/layout.tsx to trigger ISR.
  `);
}

// ─── Link image URL to the correct DB table ───────────────────────────────────

async function linkImageToRecord(
  db: ReturnType<typeof getDb>,
  item: ImageManifestItem,
  url: string,
  mediaId: number,
) {
  switch (item.targetTable) {
    case "productCategories": {
      await db
        .update(schema.productCategories)
        .set({ imageSrcUrl: url } as Partial<typeof schema.productCategories.$inferInsert>)
        .where(eq(schema.productCategories.slug, item.targetKey));
      break;
    }

    case "products": {
      await db
        .update(schema.products)
        .set({ coverMediaId: mediaId } as Partial<typeof schema.products.$inferInsert>)
        .where(eq(schema.products.slug, item.targetKey));
      break;
    }

    case "blogPosts": {
      await db
        .update(schema.blogPosts)
        .set({ coverMediaId: mediaId } as Partial<typeof schema.blogPosts.$inferInsert>)
        .where(eq(schema.blogPosts.slug, item.targetKey));
      break;
    }

    case "pageModules": {
      // Update payloadJson to include imageUrl
      const [mod] = await db
        .select()
        .from(schema.pageModules)
        .where(eq(schema.pageModules.moduleKey, item.targetKey))
        .limit(1);

      if (mod) {
        const updatedPayload = { ...(mod.payloadJson ?? {}), imageUrl: url, imageMediaId: mediaId };
        await db
          .update(schema.pageModules)
          .set({ payloadJson: updatedPayload })
          .where(eq(schema.pageModules.id, mod.id));
      }
      break;
    }

    case "siteSettings": {
      await db
        .update(schema.siteSettings)
        .set({ ogImageUrl: url } as Partial<typeof schema.siteSettings.$inferInsert>);
      break;
    }
  }
}

main().catch((err) => {
  console.error("\n❌ Fatal error:", err.message ?? err);
  process.exit(1);
});
