"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BatteryCharging, CircuitBoard, Globe2, ShieldCheck, Sparkles, Smartphone, Truck } from "lucide-react";
import type { HomePageProps } from "@/templates/types";

const EASE = [0.22, 1, 0.36, 1] as const;
const fv = (i: number) => ({ initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.5, delay: i * 0.08, ease: EASE } }) as const;
const str = (p: Record<string, unknown>, k: string) => (typeof p[k] === "string" ? (p[k] as string) : "");
const arr = (p: Record<string, unknown>, k: string) => (Array.isArray(p[k]) ? (p[k] as string[]) : []);

export function Template11HomePage({ modules, products, categories, blogPosts }: HomePageProps) {
  return (
    <div className="t11 bg-[#070b14] text-slate-50 antialiased">
      <style>{`.t11-wrap{max-width:1240px;margin:0 auto;padding:0 24px}.t11-sec{padding:92px 0}.t11-tag{display:inline-flex;align-items:center;gap:8px;padding:5px 14px;border:1px solid rgba(148,163,184,.22);border-radius:999px;background:rgba(15,23,42,.55);color:#7dd3fc;font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.t11-card{background:linear-gradient(180deg,rgba(15,23,42,.92),rgba(2,6,23,.92));border:1px solid rgba(148,163,184,.16);border-radius:20px;overflow:hidden;box-shadow:0 24px 60px rgba(2,6,23,.25)}.t11-panel{background:rgba(15,23,42,.7);border:1px solid rgba(148,163,184,.14);border-radius:24px}`}</style>
      {modules.map((m) => {
        const p = (m.payloadJson ?? {}) as Record<string, unknown>;
        if (m.moduleKey === "hero") {
          return <section key="hero" className="t11-sec relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(34,211,238,.16),transparent_42%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,.14),transparent_30%)]" /><div className="t11-wrap relative z-10 grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><span {...fv(0)} className="t11-tag mb-6"><Sparkles className="h-4 w-4" />{str(p, "eyebrow") || "Consumer Electronics Manufacturer"}</span><motion.h1 {...fv(1)} className="max-w-3xl text-5xl font-black leading-[1.04] tracking-tight md:text-7xl">{str(p, "title") || "Smart Consumer Electronics Built for Modern Retail and Global DTC Brands"}</motion.h1><motion.p {...fv(2)} className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{str(p, "description") || "From product concept and industrial design to mass production, packaging, and export readiness, we support fast-moving electronics programs end to end."}</motion.p><motion.div {...fv(3)} className="mt-10 flex flex-wrap gap-4"><Link href={str(p, "primaryCtaHref") || "/contact"} className="inline-flex items-center gap-2 rounded-full bg-cyan-400 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-slate-950 hover:bg-cyan-300">{str(p, "primaryCtaLabel") || "Request OEM Quote"}<ArrowRight className="h-4 w-4" /></Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-slate-600 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-slate-100 hover:bg-slate-900">Browse Products</Link></motion.div></div><motion.div {...fv(1)} className="t11-panel p-6"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-950/60 p-5"><Smartphone className="h-6 w-6 text-cyan-300" /><h3 className="mt-4 text-lg font-bold">Mobile-first devices</h3><p className="mt-2 text-sm leading-6 text-slate-300">Wearables, accessories, and connected devices designed for retail-ready launches.</p></div><div className="rounded-2xl bg-slate-950/60 p-5"><CircuitBoard className="h-6 w-6 text-cyan-300" /><h3 className="mt-4 text-lg font-bold">Electronics assembly</h3><p className="mt-2 text-sm leading-6 text-slate-300">Reliable SMT, assembly, testing, and packaging workflows for export buyers.</p></div><div className="rounded-2xl bg-slate-950/60 p-5"><BatteryCharging className="h-6 w-6 text-cyan-300" /><h3 className="mt-4 text-lg font-bold">Power and battery focus</h3><p className="mt-2 text-sm leading-6 text-slate-300">We support product programs with charging and battery integration needs.</p></div><div className="rounded-2xl bg-slate-950/60 p-5"><ShieldCheck className="h-6 w-6 text-cyan-300" /><h3 className="mt-4 text-lg font-bold">Quality assurance</h3><p className="mt-2 text-sm leading-6 text-slate-300">Testing, compliance prep, and packaging controls for market launch readiness.</p></div></div></motion.div></div></section>;
        }
        if (m.moduleKey === "trust-signals") {
          const items = arr(p, "items").length ? arr(p, "items") : ["OEM / ODM development support", "Retail and e-commerce packaging", "Export compliance guidance"];
          return <section key="trust-signals" className="border-y border-slate-800 bg-slate-950/60 py-7"><div className="t11-wrap flex flex-wrap items-center justify-center gap-8 md:justify-between">{items.map((it, i) => <motion.div key={i} {...fv(i)} className="flex items-center gap-3 text-sm text-slate-300"><Globe2 className="h-4 w-4 text-cyan-300" /><span>{it}</span></motion.div>)}</div></section>;
        }
        if (m.moduleKey === "featured-categories") {
          const slugs = arr(p, "slugs");
          const featured = slugs.length ? categories.filter((c) => slugs.includes(c.slug)) : categories.slice(0, 4);
          if (!featured.length) return null;
          return <section key="featured-categories" className="t11-sec"><div className="t11-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t11-tag">Product Categories</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Electronics <span className="text-cyan-300">Categories</span> for Fast Programs</h2><p className="mt-4 max-w-2xl text-slate-300">A focused assortment of consumer electronics categories designed for modern marketplaces, launches, and repeat orders.</p></motion.div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{featured.map((c, i) => <motion.div key={c.slug} {...fv(i)}><Link href={`/products/${c.slug}`} className="t11-card block h-full p-6 transition-transform hover:-translate-y-1"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><Truck className="h-6 w-6" /></div><h3 className="text-xl font-bold">{c.nameEn}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{c.summaryEn}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-cyan-300">Explore <ArrowRight className="h-3.5 w-3.5" /></span></Link></motion.div>)}</div></div></section>;
        }
        return null;
      })}
      {products.length > 0 && <section className="t11-sec border-t border-slate-800 bg-[#050814]"><div className="t11-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t11-tag">Featured Products</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Launch-Ready Products</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{products.slice(0, 6).map((p, i) => <motion.div key={p.slug} {...fv(i)}><Link href={`/products/${p.categorySlug}/${p.slug}`} className="t11-card block h-full overflow-hidden"><div className="relative aspect-[4/3] bg-slate-900">{p.coverImageUrl ? <img src={p.coverImageUrl} alt={p.coverImageAlt ?? p.nameEn} className="h-full w-full object-cover" /> : <div className="absolute inset-0 flex items-center justify-center text-cyan-300"><Sparkles className="h-12 w-12" /></div>}</div><div className="p-6"><h3 className="text-lg font-bold">{p.nameEn}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-300">{p.shortDescriptionEn ?? ""}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-cyan-300">View Details <ArrowRight className="h-3.5 w-3.5" /></span></div></Link></motion.div>)}</div></div></section>}
      {blogPosts.length > 0 && <section className="t11-sec"><div className="t11-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t11-tag">Insights</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Electronics Sourcing Guides</h2></motion.div><div className="grid gap-6 lg:grid-cols-3">{blogPosts.slice(0, 3).map((b, i) => <motion.article key={b.slug} {...fv(i)} className="t11-card p-7"><Link href={`/blog/${b.slug}`}><h3 className="text-lg font-semibold leading-7">{b.titleEn}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-300">{b.excerptEn ?? ""}</p></Link></motion.article>)}</div></div></section>}
    </div>
  );
}
