"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck, Bolt, Boxes, CheckCircle2, ChevronRight, Cog, Factory, ShieldCheck, Wrench } from "lucide-react";
import type { HomePageProps } from "@/templates/types";

const EASE = [0.22, 1, 0.36, 1] as const;
const fv = (i: number) => ({ initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.5, delay: i * 0.08, ease: EASE } }) as const;
const str = (p: Record<string, unknown>, k: string) => (typeof p[k] === "string" ? (p[k] as string) : "");
const arr = (p: Record<string, unknown>, k: string) => (Array.isArray(p[k]) ? (p[k] as string[]) : []);

export function Template08HomePage({ modules, products, categories, blogPosts }: HomePageProps) {
  return (
    <div className="t08 bg-[#0f1218] text-white antialiased">
      <style>{`.t08-wrap{max-width:1200px;margin:0 auto;padding:0 24px}.t08-sec{padding:90px 0}.t08-tag{display:inline-block;padding:4px 12px;border:1px solid rgba(99,102,241,.45);border-radius:999px;color:#c7d2fe;background:rgba(99,102,241,.12);font-size:.72rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.t08-card{background:#171d26;border:1px solid #2f353e;border-radius:10px;overflow:hidden;transition:all .2s}.t08-card:hover{transform:translateY(-4px);border-color:#6366f1}`}</style>
      {modules.map((m) => {
        const p = (m.payloadJson ?? {}) as Record<string, unknown>;
        if (m.moduleKey === "hero") return <section key="hero" className="t08-sec"><div className="t08-wrap"><motion.span {...fv(0)} className="t08-tag mb-6 inline-block">{str(p, "eyebrow") || "Hardware & Plastics Supplier"}</motion.span><motion.h1 {...fv(1)} className="mb-5 max-w-3xl text-5xl font-black leading-[1.08] md:text-6xl">{str(p, "title") || "Precision Hardware and Plastic Components for OEM Production"}</motion.h1><motion.p {...fv(2)} className="mb-10 max-w-2xl text-lg text-slate-300">{str(p, "description") || "Stable quality, tight tolerance, and project-based export support for industrial buyers."}</motion.p><motion.div {...fv(3)} className="flex flex-wrap gap-4"><Link href={str(p, "primaryCtaHref") || "/contact"} className="inline-flex items-center gap-2 rounded bg-indigo-600 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-white hover:bg-indigo-500">{str(p, "primaryCtaLabel") || "Request Quote"}<ArrowRight className="h-4 w-4" /></Link><Link href="/products" className="inline-flex items-center gap-2 rounded border border-indigo-400/40 px-8 py-3.5 text-sm font-semibold uppercase tracking-wider text-indigo-200 hover:border-indigo-300">View Products<ChevronRight className="h-4 w-4" /></Link></motion.div></div></section>;
        if (m.moduleKey === "trust-signals") {
          const items = arr(p, "items").length ? arr(p, "items") : ["CNC and injection molding workflow", "PPAP/inspection report support", "Flexible MOQ for pilot orders"];
          return <section key="trust-signals" className="border-y border-[#2f353e] bg-[#141923] py-7"><div className="t08-wrap flex flex-wrap items-center justify-center gap-8 md:justify-between">{items.map((it, i) => <motion.div key={i} {...fv(i)} className="flex items-center gap-3 text-sm text-indigo-100"><span className="text-indigo-300">{[<Cog key="a" className="h-5 w-5" />, <Wrench key="b" className="h-5 w-5" />, <Boxes key="c" className="h-5 w-5" />][i % 3]}</span><span>{it}</span></motion.div>)}</div></section>;
        }
        if (m.moduleKey === "featured-categories") {
          const slugs = arr(p, "slugs");
          const featured = slugs.length ? categories.filter((c) => slugs.includes(c.slug)) : categories.slice(0, 4);
          if (!featured.length) return null;
          return <section key="featured-categories" className="t08-sec"><div className="t08-wrap"><motion.div {...fv(0)} className="mb-14"><span className="t08-tag">Product Families</span><h2 className="mt-4 text-3xl font-black md:text-4xl">Hardware <span className="text-indigo-300">& Plastic Parts</span></h2></motion.div><div className="grid gap-6 sm:grid-cols-2">{featured.map((c, i) => <motion.div key={c.slug} {...fv(i)}><Link href={`/products/${c.slug}`} className="t08-card block h-full p-7"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded bg-indigo-500/15 text-indigo-300"><Bolt className="h-5 w-5" /></div><h3 className="mb-2 text-xl font-bold">{c.nameEn}</h3><p className="mb-5 text-sm text-slate-300">{c.summaryEn}</p><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-300">Explore <ArrowRight className="h-3.5 w-3.5" /></span></Link></motion.div>)}</div></div></section>;
        }
        if (m.moduleKey === "factory-capability") {
          return <section key="factory-capability" className="t08-sec border-y border-[#2f353e] bg-[#141923]"><div className="t08-wrap"><div className="grid gap-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><motion.div {...fv(0)}><span className="t08-tag">Factory Capability</span><h2 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">Production Controls for Repeatable Quality</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-300">{str(p, "description") || "Machining, molding, finishing, and assembly coordinated for stable output and export delivery."}</p><ul className="mt-8 space-y-3">{["Mold design and tooling support","CNC / injection workflow control","Incoming material inspection","Packaging and shipment readiness"].map((item) => <li key={item} className="flex items-start gap-3 text-sm text-slate-200"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-indigo-300" />{item}</li>)}</ul></motion.div><motion.div {...fv(1)} className="grid grid-cols-2 gap-4">{[{icon:<Factory className="h-6 w-6"/>,val:"12,000㎡",lbl:"Workshop Area"},{icon:<BadgeCheck className="h-6 w-6"/>,val:"60+",lbl:"QC Staff"},{icon:<ShieldCheck className="h-6 w-6"/>,val:"30+",lbl:"Export Markets"},{icon:<Wrench className="h-6 w-6"/>,val:"18-35d",lbl:"Lead Time"}].map((s)=><div key={s.lbl} className="t08-card p-6"><div className="text-indigo-300">{s.icon}</div><div className="mt-3 text-2xl font-black">{s.val}</div><div className="mt-1 text-xs uppercase tracking-widest text-slate-400">{s.lbl}</div></div>)}</motion.div></div></div></section>;
        }
        if (m.moduleKey === "quality-certifications") {
          return <section key="quality-certifications" className="t08-sec"><div className="t08-wrap"><motion.div {...fv(0)} className="mb-10"><span className="t08-tag">Quality & Compliance</span><h2 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">Inspection and Compliance Support</h2></motion.div><div className="grid gap-6 md:grid-cols-3">{["Material traceability","Dimensional inspection reports","RoHS / REACH support"].map((item, i)=><motion.div key={item} {...fv(i)} className="t08-card p-6"><ShieldCheck className="h-6 w-6 text-indigo-300" /><h3 className="mt-4 text-base font-bold">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-300">Controls that help keep OEM orders consistent and easier to approve.</p></motion.div>)}</div></div></section>;
        }
        if (m.moduleKey === "process-steps") {
          const items = arr(p, "items").length ? arr(p, "items") : ["Requirement review", "Tooling and sample approval", "Production and QA", "Packing and shipment"];
          return <section key="process-steps" className="t08-sec border-y border-[#2f353e] bg-[#141923]"><div className="t08-wrap"><motion.div {...fv(0)} className="mb-12 text-center"><span className="t08-tag">Delivery Process</span><h2 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">From RFQ to Shipment</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{items.map((step, i)=><motion.div key={step} {...fv(i)} className="t08-card p-6"><div className="mb-3 text-3xl font-black text-indigo-400/40">{`0${i+1}`}</div><p className="text-sm text-slate-200">{step}</p></motion.div>)}</div></div></section>;
        }
        return null;
      })}
      {products.length > 0 && <section className="t08-sec border-y border-[#2f353e] bg-[#141923]"><div className="t08-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t08-tag">Featured Products</span><h2 className="mt-4 text-3xl font-black md:text-4xl">OEM Component Lineup</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0, 6).map((p, i) => <motion.div key={p.slug} {...fv(i)}><Link href={`/products/${p.categorySlug}/${p.slug}`} className="t08-card block h-full"><div className="relative aspect-[4/3] bg-[#232a36]">{p.coverImageUrl ? <img src={p.coverImageUrl} alt={p.coverImageAlt ?? p.nameEn} className="h-full w-full object-cover opacity-90" /> : <div className="absolute inset-0 flex items-center justify-center text-indigo-700"><Cog className="h-12 w-12" /></div>}</div><div className="p-5"><h3 className="mb-1 text-base font-bold">{p.nameEn}</h3><p className="mb-4 line-clamp-2 text-xs text-slate-300">{p.shortDescriptionEn ?? ""}</p><span className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-indigo-300">Details<ChevronRight className="h-3.5 w-3.5" /></span></div></Link></motion.div>)}</div></div></section>}
      {blogPosts.length > 0 && <section className="t08-sec"><div className="t08-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t08-tag">Insights</span><h2 className="mt-4 text-3xl font-black md:text-4xl">Engineering Notes</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{blogPosts.slice(0, 3).map((b, i) => <motion.div key={b.slug} {...fv(i)} className="t08-card p-7"><Link href={`/blog/${b.slug}`}><h3 className="mb-2 text-base font-semibold">{b.titleEn}</h3><p className="line-clamp-2 text-sm text-slate-300">{b.excerptEn ?? ""}</p></Link></motion.div>)}</div></div></section>}
      <section className="t08-sec bg-gradient-to-r from-indigo-700 to-violet-600"><div className="t08-wrap text-center"><motion.div {...fv(0)} className="mx-auto max-w-2xl"><h2 className="mb-4 text-3xl font-black md:text-4xl">Need a custom component supplier?</h2><p className="mb-8 text-indigo-100">Send drawing specs, tolerances, material targets, and forecast volume for a tailored quote.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded bg-white px-8 py-3.5 text-sm font-black uppercase tracking-wider text-indigo-700">Send Requirements <ArrowRight className="h-4 w-4" /></Link><Link href="/request-quote" className="inline-flex items-center gap-2 rounded border border-white/50 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-white">Request Quote Form</Link></div></motion.div></div></section>
    </div>
  );
}
