"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck, Gift, HeartHandshake, Leaf, Sparkles, Star } from "lucide-react";
import type { HomePageProps } from "@/templates/types";

const EASE = [0.22, 1, 0.36, 1] as const;
const fv = (i: number) => ({ initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.5, delay: i * 0.08, ease: EASE } }) as const;
const str = (p: Record<string, unknown>, k: string) => (typeof p[k] === "string" ? (p[k] as string) : "");
const arr = (p: Record<string, unknown>, k: string) => (Array.isArray(p[k]) ? (p[k] as string[]) : []);

export function Template12HomePage({ modules, products, categories, blogPosts }: HomePageProps) {
  return (
    <div className="t12 bg-[#fffaf4] text-[#2d1f1b] antialiased">
      <style>{`.t12-wrap{max-width:1220px;margin:0 auto;padding:0 24px}.t12-sec{padding:92px 0}.t12-tag{display:inline-flex;align-items:center;gap:8px;padding:5px 14px;border:1px solid #f3d5bf;border-radius:999px;background:#fff4e8;color:#b45309;font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.t12-card{background:#fff;border:1px solid #f1dccf;border-radius:24px;overflow:hidden;box-shadow:0 18px 42px rgba(120,53,15,.08)}.t12-panel{background:#fff;border:1px solid #f1dccf;border-radius:28px;box-shadow:0 18px 42px rgba(120,53,15,.08)}`}</style>
      {modules.map((m) => {
        const p = (m.payloadJson ?? {}) as Record<string, unknown>;
        if (m.moduleKey === "hero") {
          return <section key="hero" className="t12-sec relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(251,191,36,.16),transparent_38%),radial-gradient(circle_at_bottom_right,rgba(244,114,182,.12),transparent_32%)]" /><div className="t12-wrap relative z-10 grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><span {...fv(0)} className="t12-tag mb-6"><Gift className="h-4 w-4" />{str(p, "eyebrow") || "Lifestyle Gifts Supplier"}</span><motion.h1 {...fv(1)} className="max-w-3xl text-5xl font-black leading-[1.04] tracking-tight md:text-7xl">{str(p, "title") || "Lifestyle Gifts and Creative Products That Feel Warm, Useful, and Memorable"}</motion.h1><motion.p {...fv(2)} className="mt-6 max-w-2xl text-lg leading-8 text-[#6d5447]">{str(p, "description") || "We help brands, retailers, and distributors create gift sets, stationery, and lifestyle products that balance charm, practicality, and export readiness."}</motion.p><motion.div {...fv(3)} className="mt-10 flex flex-wrap gap-4"><Link href={str(p, "primaryCtaHref") || "/contact"} className="inline-flex items-center gap-2 rounded-full bg-amber-500 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-white hover:bg-amber-400">{str(p, "primaryCtaLabel") || "Request Samples"}<ArrowRight className="h-4 w-4" /></Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-amber-200 px-8 py-3.5 text-sm font-bold uppercase tracking-wider text-amber-800 hover:bg-amber-50">Browse Products</Link></motion.div></div><motion.div {...fv(1)} className="t12-panel p-6"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[#fff8f0] p-5"><HeartHandshake className="h-6 w-6 text-amber-600" /><h3 className="mt-4 text-lg font-bold">Gift-ready programs</h3><p className="mt-2 text-sm leading-6 text-[#6d5447]">Custom sets, seasonal collections, and private label projects for gift buyers.</p></div><div className="rounded-3xl bg-[#fff8f0] p-5"><Leaf className="h-6 w-6 text-amber-600" /><h3 className="mt-4 text-lg font-bold">Eco-friendly options</h3><p className="mt-2 text-sm leading-6 text-[#6d5447]">Paper, bamboo, and reusable material options for sustainability-focused launches.</p></div><div className="rounded-3xl bg-[#fff8f0] p-5"><Sparkles className="h-6 w-6 text-amber-600" /><h3 className="mt-4 text-lg font-bold">Creative branding</h3><p className="mt-2 text-sm leading-6 text-[#6d5447]">Artwork, finishes, and packaging that make products feel premium and giftable.</p></div><div className="rounded-3xl bg-[#fff8f0] p-5"><BadgeCheck className="h-6 w-6 text-amber-600" /><h3 className="mt-4 text-lg font-bold">Consistent quality</h3><p className="mt-2 text-sm leading-6 text-[#6d5447]">QC checks, sample approval, and export packing standards keep launches smooth.</p></div></div></motion.div></div></section>;
        }
        if (m.moduleKey === "trust-signals") {
          const items = arr(p, "items").length ? arr(p, "items") : ["Private label and custom packaging", "Low-MOQ seasonal gift launches", "Sustainable material options"];
          return <section key="trust-signals" className="border-y border-[#f1dccf] bg-[#fffdf8] py-7"><div className="t12-wrap flex flex-wrap items-center justify-center gap-8 md:justify-between">{items.map((it, i) => <motion.div key={i} {...fv(i)} className="flex items-center gap-3 text-sm text-[#6d5447]"><Star className="h-4 w-4 text-amber-500" /><span>{it}</span></motion.div>)}</div></section>;
        }
        if (m.moduleKey === "featured-categories") {
          const slugs = arr(p, "slugs");
          const featured = slugs.length ? categories.filter((c) => slugs.includes(c.slug)) : categories.slice(0, 4);
          if (!featured.length) return null;
          return <section key="featured-categories" className="t12-sec"><div className="t12-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t12-tag">Product Categories</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Gift and Lifestyle <span className="text-amber-600">Collections</span></h2><p className="mt-4 max-w-2xl text-[#6d5447]">A warm, practical assortment of gift categories for brands, retailers, and sourcing teams.</p></motion.div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{featured.map((c, i) => <motion.div key={c.slug} {...fv(i)}><Link href={`/products/${c.slug}`} className="t12-card block h-full p-6 transition-transform hover:-translate-y-1"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><Gift className="h-6 w-6" /></div><h3 className="text-xl font-bold">{c.nameEn}</h3><p className="mt-3 text-sm leading-6 text-[#6d5447]">{c.summaryEn}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-700">Explore <ArrowRight className="h-3.5 w-3.5" /></span></Link></motion.div>)}</div></div></section>;
        }
        return null;
      })}
      {products.length > 0 && <section className="t12-sec border-t border-[#f1dccf] bg-[#fffdf8]"><div className="t12-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t12-tag">Featured Products</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Best Selling Gift Items</h2></motion.div><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{products.slice(0, 6).map((p, i) => <motion.div key={p.slug} {...fv(i)}><Link href={`/products/${p.categorySlug}/${p.slug}`} className="t12-card block h-full overflow-hidden"><div className="relative aspect-[4/3] bg-[#f7ebe0]">{p.coverImageUrl ? <img src={p.coverImageUrl} alt={p.coverImageAlt ?? p.nameEn} className="h-full w-full object-cover" /> : <div className="absolute inset-0 flex items-center justify-center text-amber-300"><Gift className="h-12 w-12" /></div>}</div><div className="p-6"><h3 className="text-lg font-bold">{p.nameEn}</h3><p className="mt-2 line-clamp-2 text-sm text-[#6d5447]">{p.shortDescriptionEn ?? ""}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-700">View Details <ArrowRight className="h-3.5 w-3.5" /></span></div></Link></motion.div>)}</div></div></section>}
      {blogPosts.length > 0 && <section className="t12-sec"><div className="t12-wrap"><motion.div {...fv(0)} className="mb-12"><span className="t12-tag">Insights</span><h2 className="mt-4 text-3xl font-black md:text-5xl">Merchandising Guides</h2></motion.div><div className="grid gap-6 lg:grid-cols-3">{blogPosts.slice(0, 3).map((b, i) => <motion.article key={b.slug} {...fv(i)} className="t12-card p-7"><Link href={`/blog/${b.slug}`}><h3 className="text-lg font-semibold leading-7">{b.titleEn}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#6d5447]">{b.excerptEn ?? ""}</p></Link></motion.article>)}</div></div></section>}
    </div>
  );
}
